// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.1
// source: internal/grpc/proto/metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricType represents the type of metric
type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED MetricType = 0
	MetricType_METRIC_TYPE_COUNTER     MetricType = 1
	MetricType_METRIC_TYPE_GAUGE       MetricType = 2
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "METRIC_TYPE_COUNTER",
		2: "METRIC_TYPE_GAUGE",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED": 0,
		"METRIC_TYPE_COUNTER":     1,
		"METRIC_TYPE_GAUGE":       2,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_metrics_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_metrics_proto_rawDescGZIP(), []int{0}
}

// Metric represents a single metric
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          MetricType             `protobuf:"varint,2,opt,name=type,proto3,enum=MetricType" json:"type,omitempty"`
	Delta         *int64                 `protobuf:"varint,3,opt,name=delta,proto3,oneof" json:"delta,omitempty"`  // for counter metrics
	Value         *float64               `protobuf:"fixed64,4,opt,name=value,proto3,oneof" json:"value,omitempty"` // for gauge metrics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *Metric) GetDelta() int64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// ReportRawMetricRequest for ReportRawMetric method
type ReportRawMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricType    MetricType             `protobuf:"varint,1,opt,name=metric_type,json=metricType,proto3,enum=MetricType" json:"metric_type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRawMetricRequest) Reset() {
	*x = ReportRawMetricRequest{}
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRawMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRawMetricRequest) ProtoMessage() {}

func (x *ReportRawMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRawMetricRequest.ProtoReflect.Descriptor instead.
func (*ReportRawMetricRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *ReportRawMetricRequest) GetMetricType() MetricType {
	if x != nil {
		return x.MetricType
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *ReportRawMetricRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReportRawMetricRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ReportMetricRequest for ReportMetric method
type ReportMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetricRequest) Reset() {
	*x = ReportMetricRequest{}
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricRequest) ProtoMessage() {}

func (x *ReportMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricRequest.ProtoReflect.Descriptor instead.
func (*ReportMetricRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *ReportMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

// ReportBatchRequest for ReportBatch method
type ReportBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportBatchRequest) Reset() {
	*x = ReportBatchRequest{}
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBatchRequest) ProtoMessage() {}

func (x *ReportBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBatchRequest.ProtoReflect.Descriptor instead.
func (*ReportBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *ReportBatchRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_metrics_proto_rawDescGZIP(), []int{4}
}

var File_internal_grpc_proto_metrics_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"!internal/grpc/proto/metrics.proto\"\x83\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\x04type\x18\x02 \x01(\x0e2\v.MetricTypeR\x04type\x12\x19\n" +
	"\x05delta\x18\x03 \x01(\x03H\x00R\x05delta\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x04 \x01(\x01H\x01R\x05value\x88\x01\x01B\b\n" +
	"\x06_deltaB\b\n" +
	"\x06_value\"n\n" +
	"\x16ReportRawMetricRequest\x12,\n" +
	"\vmetric_type\x18\x01 \x01(\x0e2\v.MetricTypeR\n" +
	"metricType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"6\n" +
	"\x13ReportMetricRequest\x12\x1f\n" +
	"\x06metric\x18\x01 \x01(\v2\a.MetricR\x06metric\"7\n" +
	"\x12ReportBatchRequest\x12!\n" +
	"\ametrics\x18\x01 \x03(\v2\a.MetricR\ametrics\"\a\n" +
	"\x05Empty*Y\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13METRIC_TYPE_COUNTER\x10\x01\x12\x15\n" +
	"\x11METRIC_TYPE_GAUGE\x10\x022\x9e\x01\n" +
	"\x0eMetricsService\x122\n" +
	"\x0fReportRawMetric\x12\x17.ReportRawMetricRequest\x1a\x06.Empty\x12,\n" +
	"\fReportMetric\x12\x14.ReportMetricRequest\x1a\x06.Empty\x12*\n" +
	"\vReportBatch\x12\x13.ReportBatchRequest\x1a\x06.EmptyB\x0eZ\fgrpc/metricsb\x06proto3"

var (
	file_internal_grpc_proto_metrics_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_metrics_proto_rawDescData []byte
)

func file_internal_grpc_proto_metrics_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_metrics_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_metrics_proto_rawDesc), len(file_internal_grpc_proto_metrics_proto_rawDesc)))
	})
	return file_internal_grpc_proto_metrics_proto_rawDescData
}

var file_internal_grpc_proto_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_grpc_proto_metrics_proto_goTypes = []any{
	(MetricType)(0),                // 0: MetricType
	(*Metric)(nil),                 // 1: Metric
	(*ReportRawMetricRequest)(nil), // 2: ReportRawMetricRequest
	(*ReportMetricRequest)(nil),    // 3: ReportMetricRequest
	(*ReportBatchRequest)(nil),     // 4: ReportBatchRequest
	(*Empty)(nil),                  // 5: Empty
}
var file_internal_grpc_proto_metrics_proto_depIdxs = []int32{
	0, // 0: Metric.type:type_name -> MetricType
	0, // 1: ReportRawMetricRequest.metric_type:type_name -> MetricType
	1, // 2: ReportMetricRequest.metric:type_name -> Metric
	1, // 3: ReportBatchRequest.metrics:type_name -> Metric
	2, // 4: MetricsService.ReportRawMetric:input_type -> ReportRawMetricRequest
	3, // 5: MetricsService.ReportMetric:input_type -> ReportMetricRequest
	4, // 6: MetricsService.ReportBatch:input_type -> ReportBatchRequest
	5, // 7: MetricsService.ReportRawMetric:output_type -> Empty
	5, // 8: MetricsService.ReportMetric:output_type -> Empty
	5, // 9: MetricsService.ReportBatch:output_type -> Empty
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_metrics_proto_init() }
func file_internal_grpc_proto_metrics_proto_init() {
	if File_internal_grpc_proto_metrics_proto != nil {
		return
	}
	file_internal_grpc_proto_metrics_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_metrics_proto_rawDesc), len(file_internal_grpc_proto_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_metrics_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_metrics_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_metrics_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_metrics_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_metrics_proto = out.File
	file_internal_grpc_proto_metrics_proto_goTypes = nil
	file_internal_grpc_proto_metrics_proto_depIdxs = nil
}
