// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: internal/grpc/proto/metrics.proto

package metrics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsService_ReportRawMetric_FullMethodName = "/MetricsService/ReportRawMetric"
	MetricsService_ReportMetric_FullMethodName    = "/MetricsService/ReportMetric"
	MetricsService_ReportBatch_FullMethodName     = "/MetricsService/ReportBatch"
)

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetricsService defines the gRPC service for metrics reporting
type MetricsServiceClient interface {
	// ReportRawMetric reports a raw metric with string value
	ReportRawMetric(ctx context.Context, in *ReportRawMetricRequest, opts ...grpc.CallOption) (*Empty, error)
	// ReportMetric reports a single structured metric
	ReportMetric(ctx context.Context, in *ReportMetricRequest, opts ...grpc.CallOption) (*Empty, error)
	// ReportBatch reports multiple metrics in batch
	ReportBatch(ctx context.Context, in *ReportBatchRequest, opts ...grpc.CallOption) (*Empty, error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) ReportRawMetric(ctx context.Context, in *ReportRawMetricRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MetricsService_ReportRawMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) ReportMetric(ctx context.Context, in *ReportMetricRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MetricsService_ReportMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) ReportBatch(ctx context.Context, in *ReportBatchRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MetricsService_ReportBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServiceServer is the server API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forward compatibility.
//
// MetricsService defines the gRPC service for metrics reporting
type MetricsServiceServer interface {
	// ReportRawMetric reports a raw metric with string value
	ReportRawMetric(context.Context, *ReportRawMetricRequest) (*Empty, error)
	// ReportMetric reports a single structured metric
	ReportMetric(context.Context, *ReportMetricRequest) (*Empty, error)
	// ReportBatch reports multiple metrics in batch
	ReportBatch(context.Context, *ReportBatchRequest) (*Empty, error)
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServiceServer struct{}

func (UnimplementedMetricsServiceServer) ReportRawMetric(context.Context, *ReportRawMetricRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRawMetric not implemented")
}
func (UnimplementedMetricsServiceServer) ReportMetric(context.Context, *ReportMetricRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMetric not implemented")
}
func (UnimplementedMetricsServiceServer) ReportBatch(context.Context, *ReportBatchRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportBatch not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}
func (UnimplementedMetricsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_ReportRawMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRawMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).ReportRawMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_ReportRawMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).ReportRawMetric(ctx, req.(*ReportRawMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_ReportMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).ReportMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_ReportMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).ReportMetric(ctx, req.(*ReportMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_ReportBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).ReportBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_ReportBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).ReportBatch(ctx, req.(*ReportBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportRawMetric",
			Handler:    _MetricsService_ReportRawMetric_Handler,
		},
		{
			MethodName: "ReportMetric",
			Handler:    _MetricsService_ReportMetric_Handler,
		},
		{
			MethodName: "ReportBatch",
			Handler:    _MetricsService_ReportBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/proto/metrics.proto",
}
